version: '3.9'
services:
  keycloak-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloakdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - microservices

  keycloak:
    image: jboss/keycloak:latest
    restart: on-failure
    command:
      - "-b"
      - "0.0.0.0"
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.provider=dir"
      - "-Dkeycloak.migration.dir=/config/"
      - "-Dkeycloak.migration.strategy=IGNORE_EXISTING"
    volumes:
      - ./config:/config/
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
      - DB_VENDOR=postgres
      - DB_USER=admin
      - DB_PASSWORD=password
      - DB_ADDR=keycloak-db
      - DB_PORT=5432
      - DB_DATABASE=keycloakdb
    ports:
      - "8081:8080"
    depends_on:
      - keycloak-db
    networks:
      - microservices

  ui-service:
    image: lsefiane/ui-service:latest
    container_name: ui-service
    restart: always
    build:
      context: .
      dockerfile: docker/ui-service/Dockerfile
    ports:
      - '8080:8080'
    networks:
      - microservices


volumes:
  pgdata:

networks:
  microservices:

